---
name: Locale-Maketext-TieHash-nbsp
version: 1.01
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
abstract: Tying subroutine to a hash
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Params::Validate: 0
  Tie::Sub: 0.07
  parent: 0
  perl: 5.006001
build_requires:
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Simple: 0
recommends:
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Locale::Maketext::TieHash::nbsp:
    file: lib/Locale/Maketext/TieHash/nbsp.pm
    version: 1.01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
